# Array Creation Functions

In [1]:
import numpy as np

In [2]:
# create an array from a list

a = np.array([1,2,3])
print("Array a:" , a)

Array a: [1 2 3]


In [3]:
b = np.arange(0,10,3)
print("Array b:",b)

Array b: [0 3 6 9]


In [4]:
d = np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d = np.zeros((2,3),dtype = int)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
e = np.ones((3,2))
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
f = np.eye(4)
print("Identity Matrix f:\n",f)

Identity Matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array manipulation function

In [8]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [9]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [10]:
# flatten an array

f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [12]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked =np.hstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [1 2 3 4]


In [13]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked =np.vstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [[1 2]
 [3 4]]


# Math operation in array(Mathematical Function)


In [14]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [15]:
squared = np.power(g,2)
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [16]:
sqrt_val = np.sqrt(g)
print("square root of g:",sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [17]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [18]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g)
print("Dot product of a1 and a :",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [ ]:
print(a)
print(a1)

In [ ]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
print("Dot product of a1 and a :",dot_product)

# Statistical in numpy 

In [19]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [20]:
var = np.var(s)
print("variance of s:",var)

variance of s: 1.25


In [21]:
std_dev = np.std(s)
print("Standaed deviation of s:",std_dev)

Standaed deviation of s: 1.118033988749895


In [22]:
s

array([1, 2, 3, 4])

In [23]:
minimum = np.min(s)
print("Minimum of s :",minimum)

Minimum of s : 1


In [24]:
maximum = np.max(s)
print("Maximun of s :",maximum)

Maximun of s : 4


# linear algebra function

# Random sampling function

In [39]:
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.43758721 0.891773   0.96366276]


In [37]:
np.random.seed(0)
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [27]:

rand_ints = np.random.randint(0,10,size=4)
print("Random integers:",rand_ints)

Random integers: [3 7 9 3]


In [28]:
np.random.seed(0)

rand_ints = np.random.randint(0,10,size=5)
print("Random Integers:",rand_ints)

Random Integers: [5 0 3 3 7]


# 1- Round

In [30]:
arr  = np.array([1.2,2.7,3.5,4.9])
round_arr = np.round(arr)
print(round_arr)

[1. 3. 4. 5.]


In [34]:
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)


[1.23 2.57 3.89]


In [36]:
np.round(np.random.random((2,3))*100)

array([[79., 53., 57.],
       [93.,  7.,  9.]])