In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5,]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
# how to convert list to array

arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(5,100,10)


array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [11]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [12]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.zeros(5) #1D array (Parametre tunning)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5, dtype = int)  #float to int convert  ( Hyperparameter Tunning)

array([0, 0, 0, 0, 0])

In [15]:
# # what is mean by parameter tunning & hyperparameter tunning
# # parameter tunning -- what system given automatically
# # Hyperparameter tunning-- if user change the system parameter


# laptop inbulid os windoe 11 -- (parametre)

# window 10 - (Hyperparameter) 

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.zeros((10,3) ,dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((10,10) ,dtype = int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(4)#(Parameter Tunning) got float

array([1., 1., 1., 1.])

In [21]:
np.ones((2,3),dtype = int)  #(Hyperparametre tunning) got int value

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [ ]:
np.three((2,3))

In [ ]:
rand(2,3)

In [ ]:
random.rand(2,3)

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(2)


In [ ]:
np.random.rand(2,3)


In [ ]:
np.random.rand((2,3), dtype = int)


In [ ]:
np.random.rand(2) -- it will generate only float value
np.random.randint(2) - it will generate only 


In [ ]:
np.random.randint(2)


In [ ]:
np.random.randint(2,9)


In [ ]:
np.random.randint(2,9,4) # Generate random integer between 2 -9 where 9 excute

In [ ]:
import numpy as np

def generate_otp(length = 4):
    otp = ''.join([str(np.random.randint(0,10)) for _ in range(length)])
    return otp

print("Your OTP is:", generate_otp())

In [ ]:
np.random.randint(10,40,(10,10))

In [ ]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

In [ ]:
print(arr1)



In [ ]:
arr1[5]

In [ ]:
arr2 = np.random.randint(2,9,(5,7))
print(arr2)

In [ ]:
arr2[-3]

In [ ]:
arr2

In [ ]:
arr2[2:10]

In [ ]:
arr2

In [ ]:
arr2[:]

In [ ]:
arr2[::-1]

In [ ]:
arr2

In [ ]:
arr2[::3]

In [ ]:
arr2

In [ ]:
arr2[3,4]

In [ ]:
print(arr2[3,4])


In [ ]:
arr2

In [ ]:
print(arr2[-4,-5])

In [ ]:
arr2

In [ ]:
arr2[0,1] = 10

In [ ]:
arr2

In [ ]:
arr2[:,0]

In [ ]:
arr2[:,4]

In [ ]:
arr2

In [ ]:
arr2[:,-3]

In [ ]:
arr2[:,-1]

In [ ]:
arr2[4]

In [ ]:
arr2

In [ ]:
arr2[1:2,1:2]

In [ ]:
# masking or filter in numpy

In [ ]:
arr2

In [ ]:
arr2 > 5

In [ ]:
arr2[arr2 > 5]

In [ ]:
arr2[arr2>=5]

In [ ]:
arr2

In [ ]:
arr2[arr2 == 5]

In [ ]:
arr2[arr2 !=5]

In [ ]:
arr1

In [ ]:
arr

In [23]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [25]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
arr

array([0, 1, 2, 3, 4, 5])

In [27]:
arr[arr.max()]

np.int64(5)

In [28]:
arr.min()

np.int64(0)

In [29]:
arr2.max()

NameError: name 'arr2' is not defined

In [31]:
arr1.min()

NameError: name 'arr1' is not defined

In [32]:
arr1.max()

NameError: name 'arr1' is not defined