In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5,]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
# how to convert list to array

arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(5,100,10)


array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [11]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [12]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.zeros(5) #1D array (Parametre tunning)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5, dtype = int)  #float to int convert  ( Hyperparameter Tunning)

array([0, 0, 0, 0, 0])

In [15]:
# # what is mean by parameter tunning & hyperparameter tunning
# # parameter tunning -- what system given automatically
# # Hyperparameter tunning-- if user change the system parameter


# laptop inbulid os windoe 11 -- (parametre)

# window 10 - (Hyperparameter) 

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.zeros((10,3) ,dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((10,10) ,dtype = int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(4)#(Parameter Tunning) got float

array([1., 1., 1., 1.])

In [21]:
np.ones((2,3),dtype = int)  #(Hyperparametre tunning) got int value

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [ ]:
np.three((2,3))

In [ ]:
rand(2,3)

In [23]:
random.rand(2,3)

NameError: name 'random' is not defined

In [24]:
np.random.rand(2)

array([0.71474701, 0.63981285])

In [25]:
np.random.rand(2)


array([0.67442748, 0.66168203])

In [26]:
np.random.rand(2,3)


array([[0.85404039, 0.16998201, 0.88234686],
       [0.98936778, 0.41682902, 0.37519458]])

In [27]:
np.random.rand((2,3), dtype = int)


TypeError: rand() got an unexpected keyword argument 'dtype'

In [28]:
np.random.rand(2) -- it will generate only float value
np.random.randint(2) - it will generate only 


SyntaxError: invalid syntax (4182842919.py, line 1)

In [29]:
np.random.randint(2)


1

In [30]:
np.random.randint(2,9)


3

In [31]:
np.random.randint(2,9,4) # Generate random integer between 2 -9 where 9 excute

array([4, 7, 2, 7], dtype=int32)

In [34]:
import numpy as np

def generate_otp(length = 4):
    otp = ''.join([str(np.random.randint(0,10)) for _ in range(length)])
    return otp

print("Your OTP is:", generate_otp())

Your OTP is: 2763


In [97]:
np.random.randint(10,40,(10,10))

array([[39, 18, 33, 33, 20, 10, 15, 12, 16, 19],
       [28, 33, 23, 22, 12, 24, 21, 39, 36, 15],
       [19, 26, 38, 16, 21, 36, 10, 33, 32, 35],
       [22, 13, 31, 22, 39, 34, 14, 26, 17, 31],
       [29, 11, 31, 13, 28, 33, 34, 39, 31, 23],
       [34, 18, 26, 36, 16, 27, 22, 25, 20, 26],
       [30, 12, 11, 10, 15, 11, 15, 23, 34, 32],
       [29, 26, 38, 39, 21, 25, 22, 25, 18, 21],
       [13, 38, 31, 11, 18, 23, 19, 12, 19, 11],
       [23, 34, 32, 31, 29, 12, 23, 19, 31, 12]], dtype=int32)

In [93]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

[[36 37 39 25 19 12 25 34 19 37]
 [24 25 29 32 28 21 25 19 14 28]
 [35 19 23 38 12 22 28 10 21 32]
 [17 10 26 25 10 26 39 32 12 18]
 [13 17 30 26 17 23 32 23 13 13]
 [14 27 23 28 16 15 14 16 14 39]
 [28 39 29 21 28 38 33 14 28 23]
 [37 25 16 34 20 20 15 28 17 34]
 [27 16 37 14 35 31 29 10 19 20]
 [39 35 16 28 19 21 35 37 31 13]]


In [40]:
print(arr1)



[[17 36 33 10 32 32 18 21 32 11]
 [15 25 14 39 31 22 13 28 19 15]
 [36 38 34 14 18 36 13 26 23 28]
 [13 39 10 25 24 39 38 14 19 20]
 [18 34 10 37 22 13 32 15 36 11]
 [16 24 39 16 10 19 19 12 15 10]
 [32 15 32 10 30 23 24 10 29 13]
 [19 15 37 26 28 11 30 20 15 39]
 [18 29 21 12 24 32 38 39 22 16]
 [23 11 37 34 34 34 14 33 13 22]]


In [41]:
arr1[5]

array([16, 24, 39, 16, 10, 19, 19, 12, 15, 10], dtype=int32)

In [43]:
arr2 = np.random.randint(2,9,(5,7))
print(arr2)

[[6 7 7 7 5 7 8]
 [7 7 5 4 6 2 3]
 [5 7 2 6 7 8 8]
 [3 3 7 3 5 5 3]
 [5 8 2 6 2 4 2]]


In [44]:
arr2[-3]

array([5, 7, 2, 6, 7, 8, 8], dtype=int32)

In [45]:
arr2

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [46]:
arr2[2:10]

array([[5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [47]:
arr2

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [48]:
arr2[:]

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [49]:
arr2[::-1]

array([[5, 8, 2, 6, 2, 4, 2],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [6, 7, 7, 7, 5, 7, 8]], dtype=int32)

In [50]:
arr2

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [51]:
arr2[::3]

array([[6, 7, 7, 7, 5, 7, 8],
       [3, 3, 7, 3, 5, 5, 3]], dtype=int32)

In [52]:
arr2

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [53]:
arr2[3,4]

np.int32(5)

In [54]:
print(arr2[3,4])


5


In [55]:
arr2

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [56]:
print(arr2[-4,-5])

5


In [57]:
arr2

array([[6, 7, 7, 7, 5, 7, 8],
       [7, 7, 5, 4, 6, 2, 3],
       [5, 7, 2, 6, 7, 8, 8],
       [3, 3, 7, 3, 5, 5, 3],
       [5, 8, 2, 6, 2, 4, 2]], dtype=int32)

In [58]:
arr2[0,1] = 10

In [59]:
arr2

array([[ 6, 10,  7,  7,  5,  7,  8],
       [ 7,  7,  5,  4,  6,  2,  3],
       [ 5,  7,  2,  6,  7,  8,  8],
       [ 3,  3,  7,  3,  5,  5,  3],
       [ 5,  8,  2,  6,  2,  4,  2]], dtype=int32)

In [60]:
arr2[:,0]

array([6, 7, 5, 3, 5], dtype=int32)

In [61]:
arr2[:,4]

array([5, 6, 7, 5, 2], dtype=int32)

In [62]:
arr2

array([[ 6, 10,  7,  7,  5,  7,  8],
       [ 7,  7,  5,  4,  6,  2,  3],
       [ 5,  7,  2,  6,  7,  8,  8],
       [ 3,  3,  7,  3,  5,  5,  3],
       [ 5,  8,  2,  6,  2,  4,  2]], dtype=int32)

In [63]:
arr2[:,-3]

array([5, 6, 7, 5, 2], dtype=int32)

In [65]:
arr2[:,-1]

array([8, 3, 8, 3, 2], dtype=int32)

In [66]:
arr2[4]

array([5, 8, 2, 6, 2, 4, 2], dtype=int32)

In [67]:
arr2

array([[ 6, 10,  7,  7,  5,  7,  8],
       [ 7,  7,  5,  4,  6,  2,  3],
       [ 5,  7,  2,  6,  7,  8,  8],
       [ 3,  3,  7,  3,  5,  5,  3],
       [ 5,  8,  2,  6,  2,  4,  2]], dtype=int32)

In [72]:
arr2[1:2,1:2]

array([[7]], dtype=int32)

In [ ]:
# masking or filter in numpy

In [73]:
arr2

array([[ 6, 10,  7,  7,  5,  7,  8],
       [ 7,  7,  5,  4,  6,  2,  3],
       [ 5,  7,  2,  6,  7,  8,  8],
       [ 3,  3,  7,  3,  5,  5,  3],
       [ 5,  8,  2,  6,  2,  4,  2]], dtype=int32)

In [74]:
arr2 > 5

array([[ True,  True,  True,  True, False,  True,  True],
       [ True,  True, False, False,  True, False, False],
       [False,  True, False,  True,  True,  True,  True],
       [False, False,  True, False, False, False, False],
       [False,  True, False,  True, False, False, False]])

In [75]:
arr2[arr2 > 5]

array([ 6, 10,  7,  7,  7,  8,  7,  7,  6,  7,  6,  7,  8,  8,  7,  8,  6],
      dtype=int32)

In [76]:
arr2[arr2>=5]

array([ 6, 10,  7,  7,  5,  7,  8,  7,  7,  5,  6,  5,  7,  6,  7,  8,  8,
        7,  5,  5,  5,  8,  6], dtype=int32)

In [77]:
arr2

array([[ 6, 10,  7,  7,  5,  7,  8],
       [ 7,  7,  5,  4,  6,  2,  3],
       [ 5,  7,  2,  6,  7,  8,  8],
       [ 3,  3,  7,  3,  5,  5,  3],
       [ 5,  8,  2,  6,  2,  4,  2]], dtype=int32)

In [78]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5], dtype=int32)

In [79]:
arr2[arr2 !=5]

array([ 6, 10,  7,  7,  7,  8,  7,  7,  4,  6,  2,  3,  7,  2,  6,  7,  8,
        8,  3,  3,  7,  3,  3,  8,  2,  6,  2,  4,  2], dtype=int32)

In [80]:
arr1

array([[17, 36, 33, 10, 32, 32, 18, 21, 32, 11],
       [15, 25, 14, 39, 31, 22, 13, 28, 19, 15],
       [36, 38, 34, 14, 18, 36, 13, 26, 23, 28],
       [13, 39, 10, 25, 24, 39, 38, 14, 19, 20],
       [18, 34, 10, 37, 22, 13, 32, 15, 36, 11],
       [16, 24, 39, 16, 10, 19, 19, 12, 15, 10],
       [32, 15, 32, 10, 30, 23, 24, 10, 29, 13],
       [19, 15, 37, 26, 28, 11, 30, 20, 15, 39],
       [18, 29, 21, 12, 24, 32, 38, 39, 22, 16],
       [23, 11, 37, 34, 34, 34, 14, 33, 13, 22]], dtype=int32)

In [81]:
arr

array([0, 1, 2, 3, 4, 5])

In [82]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [83]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [84]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [87]:
arr[arr.max()]

np.int64(5)

In [88]:
arr.min()

np.int64(0)

In [89]:
arr2.max()

np.int32(10)

In [90]:
arr1.min()

np.int32(10)

In [92]:
arr1.max()

np.int32(39)